### ISSUE TITLE
is there a mac OSX version of pykml?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tylere/pykml#36]
```
What steps will reproduce the problem?
1. providing a version of pykml for mac osx
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
mac osx 10.6 python 2.6

Please provide any additional information below.


```

Original issue reported on code.google.com by `andrew.s...@gmail.com` on 2 Jan 2013 at 8:04

**Comment by tylere** [comment]
pyKML is just Python code, and should be operating system agnostic. However, it depends on lxml, which is not Python. Are you able to install lxml on your OSX system?

**Comment by tylere** [comment]
pyKML is also available via conda-forge, that can be used to install on OSX.
